<a href="https://colab.research.google.com/github/ljtallon/SQL_Projects/blob/main/Resources/Blank_SQL_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [1]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [2]:
%%sql

SELECT *
FROM sales
LIMIT 10;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64
1,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64
2,1001,0,2015-01-01,2015-01-01,1772036,430,1730,2,54.38,54.38,25.00,USD,1.00
3,1002,0,2015-01-01,2015-01-01,1518349,660,955,4,315.04,286.69,144.88,USD,1.00
4,1002,1,2015-01-01,2015-01-01,1518349,660,62,7,135.75,135.75,62.43,USD,1.00
5,1002,2,2015-01-01,2015-01-01,1518349,660,1050,3,499.20,434.30,229.57,USD,1.00
6,1002,3,2015-01-01,2015-01-01,1518349,660,1608,1,65.99,58.73,33.65,USD,1.00
7,1003,0,2015-01-01,2015-01-01,1317097,510,85,3,74.99,74.99,34.48,USD,1.00
8,1004,0,2015-01-01,2015-01-01,254117,80,128,2,114.72,113.57,58.49,CAD,1.16
9,1004,1,2015-01-01,2015-01-01,254117,80,2079,1,499.45,499.45,165.48,CAD,1.16

In [3]:
%%sql

SELECT *
FROM information_schema.columns
WHERE table_name = 'customer'

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

24 rows affected.

,table_catalog,table_schema,table_name,column_name,ordinal_position,column_default,is_nullable,data_type,character_maximum_length,character_octet_length,...,is_identity,identity_generation,identity_start,identity_increment,identity_maximum,identity_minimum,identity_cycle,is_generated,generation_expression,is_updatable
0,contoso_100k,public,customer,customerkey,1,None,NO,integer,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
1,contoso_100k,public,customer,geoareakey,2,None,YES,integer,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
2,contoso_100k,public,customer,startdt,3,None,YES,date,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
3,contoso_100k,public,customer,enddt,4,None,YES,date,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
4,contoso_100k,public,customer,birthday,18,None,YES,date,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
5,contoso_100k,public,customer,age,19,None,YES,integer,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
6,contoso_100k,public,customer,latitude,23,None,YES,double precision,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
7,contoso_100k,public,customer,longitude,24,None,YES,double precision,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
8,contoso_100k,public,customer,middleinitial,9,None,YES,character varying,5.00,20.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
9,contoso_100k,public,customer,surname,10,None,YES,character varying,50.00,200.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
10,contoso_100k,public,customer,streetaddress,11,None,YES,character varying,100.00,400.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
11,contoso_100k,public,customer,city,12,None,YES,character varying,50.00,200.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
12,contoso_100k,public,customer,state,13,None,YES,character varying,50.00,200.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
13,contoso_100k,public,customer,statefull,14,None,YES,character varying,100.00,400.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
14,contoso_100k,public,customer,zipcode,15,None,YES,character varying,20.00,80.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
15,contoso_100k,public,customer,country,16,None,YES,character varying,50.00,200.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
16,contoso_100k,public,customer,countryfull,17,None,YES,character varying,100.00,400.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
17,contoso_100k,public,customer,company,21,None,YES,character varying,100.00,400.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
18,contoso_100k,public,customer,vehicle,22,None,YES,character varying,100.00,400.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
19,contoso_100k,public,customer,occupation,20,None,YES,character varying,100.00,400.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
20,contoso_100k,public,customer,continent,5,None,YES,character varying,50.00,200.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
21,contoso_100k,public,customer,gender,6,None,YES,character varying,10.00,40.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
22,contoso_100k,public,customer,title,7,None,YES,character varying,20.00,80.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
23,contoso_100k,public,customer,givenname,8,None,YES,character varying,50.00,200.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES

In [4]:
%%sql

SELECT orderdate,
  quantity * netprice * exchangerate AS net_revenue
FROM sales
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate  net_revenue
0  2015-01-01        63.49
1  2015-01-01       423.28
2  2015-01-01       108.75
3  2015-01-01      1146.75
4  2015-01-01       950.25
5  2015-01-01      1302.91
6  2015-01-01        58.73
7  2015-01-01       224.98
8  2015-01-01       263.11
9  2015-01-01       578.52

Recent sales >= 2020

In [5]:
%%sql

SELECT orderdate,
  quantity * netprice * exchangerate AS net_revenue
FROM sales
WHERE orderdate::DATE >= '2020-01-01'
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate  net_revenue
0  2020-01-01        99.47
1  2020-01-01       139.97
2  2020-01-01       669.39
3  2020-01-01      4090.60
4  2020-01-01       237.15
5  2020-01-01      1507.16
6  2020-01-01       189.35
7  2020-01-01       539.90
8  2020-01-01      5590.00
9  2020-01-01      3580.00

Add customer info

In [6]:
%%sql

SELECT
  s.orderdate,
  s.quantity * s.netprice * s.exchangerate AS net_revenue,
  c.givenname,
  c.surname,
  c.countryfull,
  c.continent,
  p.productkey,
  p.productname,
  p.categoryname,
  p.subcategoryname
FROM
  sales AS s
LEFT JOIN customer AS c ON s.customerkey = c.customerkey
LEFT JOIN product AS p ON s.productkey = p.productkey
WHERE
  orderdate::DATE >= '2020-01-01'
LIMIT
  10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,orderdate,net_revenue,givenname,surname,countryfull,continent,productkey,productname,categoryname,subcategoryname
0,2020-01-01,99.47,Heike,Burger,Germany,Europe,1810,MGS Bicycle Card Games2009 E166,Games and Toys,Download Games
1,2020-01-01,139.97,Heike,Burger,Germany,Europe,1809,MGS Bicycle Board Games2009 E165,Games and Toys,Download Games
2,2020-01-01,669.39,Heike,Burger,Germany,Europe,698,Proseware Wireless Photo All-in-One Printer M3...,Computers,"Printers, Scanners & Fax"
3,2020-01-01,4090.60,Heike,Burger,Germany,Europe,364,Adventure Works Laptop12 M1200 Black,Computers,Laptops
4,2020-01-01,237.15,Michelle,Seeber,Canada,North America,1288,Contoso Genuine Leather Grip Belt E322 Silver,Cameras and camcorders,Cameras & Camcorders Accessories
5,2020-01-01,1507.16,Jason,Smith,United States,North America,2061,Contoso Microwave 1.5CuFt X0110 Silver,Home Appliances,Microwaves
6,2020-01-01,189.35,Jason,Smith,United States,North America,1717,MGS Flight Simulator X M250,Games and Toys,Download Games
7,2020-01-01,539.90,Jason,Smith,United States,North America,435,Adventure Works Desktop PC1.60 ED160 White,Computers,Desktops
8,2020-01-01,5590.00,James,Frye,United States,North America,451,WWI Desktop PC2.30 M2300 Silver,Computers,Desktops
9,2020-01-01,3580.00,Johnny,Couch,United States,North America,535,WWI LCD19W M100 White,Computers,Monitors

High vs low ($1,000)

In [7]:
%%sql

SELECT
  s.orderdate,
  s.quantity * s.netprice * s.exchangerate AS net_revenue,
  c.givenname,
  c.surname,
  c.countryfull,
  c.continent,
  p.productkey,
  p.productname,
  p.categoryname,
  p.subcategoryname,
  CASE WHEN s.quantity * s.netprice * s.exchangerate > 1000 THEN 'HIGH' ELSE 'LOW' END AS high_low
FROM
  sales AS s
LEFT JOIN customer AS c ON s.customerkey = c.customerkey
LEFT JOIN product AS p ON s.productkey = p.productkey
WHERE
  orderdate::DATE >= '2020-01-01'

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

124451 rows affected.

,orderdate,net_revenue,givenname,surname,countryfull,continent,productkey,productname,categoryname,subcategoryname,high_low
0,2020-01-01,336.08,Freda,Howard,Canada,North America,1360,Contoso In front of Centrex L15 White,Cell phones,Home & Office Phones,LOW
1,2020-01-01,174.65,Jan,Muller,Germany,Europe,562,Proseware Screen 80in E1010 White,Computers,Projectors & Screens,LOW
2,2020-01-02,31.46,Annett,Vogt,Germany,Europe,1779,MGS Zoo Tycoon2: Marine Mania Expansion Pack 2...,Games and Toys,Download Games,LOW
3,2020-01-02,5843.64,Annett,Vogt,Germany,Europe,422,Adventure Works Desktop PC2.33 XD233 Black,Computers,Desktops,HIGH
4,2020-01-02,1487.51,Annett,Vogt,Germany,Europe,1210,Fabrikam Business Videographer 1/3'' 8.5mm M38...,Cameras and camcorders,Camcorders,HIGH
...,...,...,...,...,...,...,...,...,...,...,...
124446,2023-09-29,219.30,Janet,Mariscal,United States,North America,31,Contoso 32GB Video MP3 Player M3200 Orange,Audio,MP4&MP3,LOW
124447,2023-09-29,117.10,Jesse,Mullawirraburka,Australia,Australia,1594,SV DVD 38 DVD Storage Binder E25 Red,"Music, Movies and Audio Books",Movie DVD,LOW
124448,2023-09-29,1591.09,Florian,Goldschmidt,Germany,Europe,1550,The Phone Company PDA Palm 3.5 inch M810 Silver,Cell phones,Smart phones & PDAs,HIGH
124449,2023-09-30,922.04,Arja,Uusitalo,United States,North America,296,SV Car Video TFT6.2W E6281 Black,TV and Video,Car Video,LOW
124450,2023-09-30,1270.36,Jacalyn,Bryant,United States,North America,443,WWI Desktop PC3.0 M0300 Silver,Computers,Desktops,HIGH

Total number of customers per order date

In [8]:
%%sql

SELECT
  orderdate,
  COUNT(DISTINCT(customerkey)) AS total_customers
FROM
  sales
WHERE
  orderdate BETWEEN '2023-01-01' AND '2023-12-31'
GROUP BY
  orderdate
ORDER BY
  orderdate

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

364 rows affected.

      orderdate  total_customers
0    2023-01-01               12
1    2023-01-02               49
2    2023-01-03               64
3    2023-01-04               78
4    2023-01-05               87
..          ...              ...
359  2023-12-27               73
360  2023-12-28               75
361  2023-12-29               55
362  2023-12-30               91
363  2023-12-31                9

[364 rows x 2 columns]

Customers by region

In [9]:
%%sql

SELECT
  s.orderdate,
  COUNT(DISTINCT CASE WHEN c.continent = 'Europe' THEN s.customerkey END) AS eu_customers,
  COUNT(DISTINCT CASE WHEN c.continent = 'North America' THEN s.customerkey END) AS na_customers,
  COUNT(DISTINCT CASE WHEN c.continent = 'Australia' THEN s.customerkey END) AS au_customers
FROM
  sales AS s
LEFT JOIN customer AS c ON s.customerkey = c.customerkey
WHERE
  s.orderdate BETWEEN '2023-01-01' AND '2023-12-31'
GROUP BY
  s.orderdate
ORDER BY
  s.orderdate

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

364 rows affected.

      orderdate  eu_customers  na_customers  au_customers
0    2023-01-01             6             5             1
1    2023-01-02            15            31             3
2    2023-01-03            17            44             3
3    2023-01-04            28            46             4
4    2023-01-05            22            57             8
..          ...           ...           ...           ...
359  2023-12-27            26            41             6
360  2023-12-28            24            44             7
361  2023-12-29            19            32             4
362  2023-12-30            25            50            16
363  2023-12-31             1             8             0

[364 rows x 4 columns]

Daily customers by region

In [10]:
%%sql

SELECT
  p.categoryname,
  SUM(CASE WHEN s.orderdate BETWEEN '2022-01-01' AND '2022-12-31' THEN (s.quantity * s.netprice * s.exchangerate) ELSE 0 END) AS total_net_revenue_2022,
  SUM(CASE WHEN s.orderdate BETWEEN '2023-01-01' AND '2023-12-31' THEN (s.quantity * s.netprice * s.exchangerate) ELSE 0 END) AS total_net_revenue_2023
FROM
  sales AS s
LEFT JOIN product AS p ON s.productkey = p.productkey
GROUP BY
  p.categoryname
ORDER BY
  p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

,categoryname,total_net_revenue_2022,total_net_revenue_2023
0,Audio,766938.21,688690.18
1,Cameras and camcorders,2382532.56,1983546.29
2,Cell phones,8119665.07,6002147.63
3,Computers,17862213.49,11650867.21
4,Games and Toys,316127.30,270374.96
5,Home Appliances,6612446.68,5919992.87
6,"Music, Movies and Audio Books",2989297.28,2180768.13
7,TV and Video,5815336.61,4412178.23

Aggregate functions with net revenue

In [11]:
%%sql

SELECT
  p.categoryname,
  AVG(CASE WHEN s.orderdate BETWEEN '2022-01-01' AND '2022-12-31' THEN (s.quantity * s.netprice * s.exchangerate) ELSE 0 END) AS avg_net_revenue_2022,
  AVG(CASE WHEN s.orderdate BETWEEN '2023-01-01' AND '2023-12-31' THEN (s.quantity * s.netprice * s.exchangerate) ELSE 0 END) AS avg_net_revenue_2023,
  MIN(CASE WHEN s.orderdate BETWEEN '2022-01-01' AND '2022-12-31' THEN (s.quantity * s.netprice * s.exchangerate) ELSE 0 END) AS min_net_revenue_2022,
  MIN(CASE WHEN s.orderdate BETWEEN '2023-01-01' AND '2023-12-31' THEN (s.quantity * s.netprice * s.exchangerate) ELSE 0 END) AS min_net_revenue_2023,
  MAX(CASE WHEN s.orderdate BETWEEN '2022-01-01' AND '2022-12-31' THEN (s.quantity * s.netprice * s.exchangerate) ELSE 0 END) AS max_net_revenue_2022,
  MAX(CASE WHEN s.orderdate BETWEEN '2023-01-01' AND '2023-12-31' THEN (s.quantity * s.netprice * s.exchangerate) ELSE 0 END) AS max_net_revenue_2023
FROM
  sales AS s
LEFT JOIN product AS p ON s.productkey = p.productkey
GROUP BY
  p.categoryname
ORDER BY
  p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

,categoryname,avg_net_revenue_2022,avg_net_revenue_2023,min_net_revenue_2022,min_net_revenue_2023,max_net_revenue_2022,max_net_revenue_2023
0,Audio,50.18,45.06,0.00,0.00,3473.36,2730.87
1,Cameras and camcorders,176.85,147.23,0.00,0.00,15008.39,13572.00
2,Cell phones,194.66,143.89,0.00,0.00,7692.37,8912.22
3,Computers,384.13,250.55,0.00,0.00,38082.66,27611.60
4,Games and Toys,15.60,13.34,0.00,0.00,5202.01,3357.30
5,Home Appliances,390.05,349.20,0.00,0.00,31654.55,32915.59
6,"Music, Movies and Audio Books",93.37,68.11,0.00,0.00,5415.19,3804.91
7,TV and Video,425.35,322.72,0.00,0.00,30259.41,27503.12

Median sales by category in postgreSQL

In [12]:
%%sql

SELECT
  p.categoryname,
  PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (CASE WHEN s.orderdate BETWEEN '2022-01-01' AND '2022-12-31' THEN (s.quantity * s.netprice * s.exchangerate) END)) AS y2022_median_sales,
  PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (CASE WHEN s.orderdate BETWEEN '2023-01-01' AND '2023-12-31' THEN (s.quantity * s.netprice * s.exchangerate) END)) AS y2023_median_sales
FROM
  sales AS s
LEFT JOIN product AS p ON s.productkey = p.productkey
GROUP BY
  p.categoryname
ORDER BY
  p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                    categoryname  y2022_median_sales  y2023_median_sales
0                          Audio              257.21              266.59
1        Cameras and camcorders               651.46              672.60
2                    Cell phones              418.60              375.88
3                      Computers              809.70              657.18
4                 Games and Toys               33.78               32.62
5                Home Appliances              791.00              825.25
6  Music, Movies and Audio Books              186.58              159.63
7                   TV and Video              730.46              790.79

Segmentation by lowest/highest revenue using median

In [13]:
%%sql

WITH median_value AS (
  SELECT
    PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (s.quantity * s.netprice *s.exchangerate)) AS median
  FROM
    sales AS s
  WHERE orderdate BETWEEN '2022-01-01' AND '2023-12-31'
)

SELECT
  p.categoryname,
  SUM(CASE WHEN (s.quantity * s.netprice *s.exchangerate) <mv.median
      AND s.orderdate BETWEEN '2022-01-01' AND '2022-12-31'
  THEN (s.quantity * s.netprice *s.exchangerate) END) AS low_net_revenue_2022,
  SUM(CASE WHEN (s.quantity * s.netprice *s.exchangerate) >=mv.median
      AND s.orderdate BETWEEN '2022-01-01' AND '2022-12-31'
  THEN (s.quantity * s.netprice *s.exchangerate) END) AS high_net_revenue_2022,
  SUM(CASE WHEN (s.quantity * s.netprice *s.exchangerate) <mv.median
      AND s.orderdate BETWEEN '2023-01-01' AND '2023-12-31'
  THEN (s.quantity * s.netprice *s.exchangerate) END) AS low_net_revenue_2023,
  SUM(CASE WHEN (s.quantity * s.netprice *s.exchangerate) >=mv.median
      AND s.orderdate BETWEEN '2023-01-01' AND '2023-12-31'
  THEN (s.quantity * s.netprice *s.exchangerate) END) AS high_net_revenue_2023
FROM
  sales AS s
LEFT JOIN product AS p ON s.productkey = p.productkey,
          median_value AS mv
GROUP BY
  p.categoryname
ORDER BY
  p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

,categoryname,low_net_revenue_2022,high_net_revenue_2022,low_net_revenue_2023,high_net_revenue_2023
0,Audio,222337.83,544600.39,180251.13,508439.06
1,Cameras and camcorders,133004.54,2249528.02,104869.46,1878676.83
2,Cell phones,814449.53,7305215.55,729699.39,5272448.24
3,Computers,624340.42,17237873.07,590790.31,11060076.90
4,Games and Toys,231979.63,84147.67,206103.36,64271.60
5,Home Appliances,219797.07,6392649.61,176261.35,5743731.52
6,"Music, Movies and Audio Books",685808.49,2303488.80,574958.76,1605809.37
7,TV and Video,272338.29,5542998.32,164275.35,4247902.87

Segmentation by IQR percentiles

In [14]:
%%sql

WITH percentiles AS (
  SELECT
    PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY (s.quantity * s.netprice *s.exchangerate)) AS revenue_25th_percentile,
    PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY (s.quantity * s.netprice *s.exchangerate)) AS revenue_75th_percentile
  FROM
    sales AS s
  WHERE orderdate BETWEEN '2022-01-01' AND '2023-12-31'
)

SELECT
  p.categoryname AS category,
  CASE
      WHEN (s.quantity * s.netprice *s.exchangerate) <= pctl.revenue_25th_percentile THEN 'LOW'
      WHEN (s.quantity * s.netprice *s.exchangerate) >= pctl.revenue_75th_percentile THEN 'HIGH'
      ELSE 'MEDIUM'
  END AS revenue_tier,
  SUM(s.quantity * s.netprice *s.exchangerate) AS total_revenue
FROM
  sales AS s
LEFT JOIN product AS p ON s.productkey = p.productkey,
          percentiles AS pctl
GROUP BY
  p.categoryname,
  revenue_tier
ORDER BY
  p.categoryname,
  revenue_tier

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

24 rows affected.

                         category revenue_tier  total_revenue
0                           Audio         HIGH     1213265.71
1                           Audio          LOW      267217.01
2                           Audio       MEDIUM     3832415.38
3         Cameras and camcorders          HIGH    15050781.63
4         Cameras and camcorders           LOW       81032.92
5         Cameras and camcorders        MEDIUM     3388546.10
6                     Cell phones         HIGH    21874993.15
7                     Cell phones          LOW      410309.35
8                     Cell phones       MEDIUM    10338963.22
9                       Computers         HIGH    79607760.89
10                      Computers          LOW      203207.06
11                      Computers       MEDIUM    10808054.11
12                 Games and Toys         HIGH      133749.09
13                 Games and Toys          LOW      533443.13
14                 Games and Toys       MEDIUM     1001381.91
15                Home Appliances         HIGH    22383475.30
16                Home Appliances          LOW      105045.60
17                Home Appliances       MEDIUM     4118724.64
18  Music, Movies and Audio Books         HIGH     3844996.29
19  Music, Movies and Audio Books          LOW      642496.71
20  Music, Movies and Audio Books       MEDIUM     6100817.99
21                   TV and Video         HIGH    16632856.33
22                   TV and Video          LOW       67221.76
23                   TV and Video       MEDIUM     3766783.30

Date formatting - DATE_TRUNC

In [15]:
%%sql

SELECT
  DATE_TRUNC('month', orderdate)::date AS order_month,
  SUM(quantity * netprice * exchangerate) AS net_revenue,
  COUNT(DISTINCT customerkey) AS total_unique_customers
FROM
  sales
GROUP BY order_month

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

112 rows affected.

    order_month  net_revenue  total_unique_customers
0    2015-01-01    384092.66                     200
1    2015-02-01    706374.12                     291
2    2015-03-01    332961.59                     139
3    2015-04-01    160767.00                      78
4    2015-05-01    548632.63                     236
..          ...          ...                     ...
107  2023-12-01   2928550.93                    1484
108  2024-01-01   2677498.55                    1340
109  2024-02-01   3542322.55                    1718
110  2024-03-01   1692854.89                     877
111  2024-04-01    483851.39                     246

[112 rows x 3 columns]

Date formatting - TO_CHAR

In [16]:
%%sql

SELECT
  TO_CHAR(orderdate, 'YYYY-MM') AS order_month,
  SUM(quantity * netprice * exchangerate) AS net_revenue,
  COUNT(DISTINCT customerkey) AS total_unique_customers
FROM
  sales
GROUP BY order_month

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

112 rows affected.

    order_month  net_revenue  total_unique_customers
0       2015-01    384092.66                     200
1       2015-02    706374.12                     291
2       2015-03    332961.59                     139
3       2015-04    160767.00                      78
4       2015-05    548632.63                     236
..          ...          ...                     ...
107     2023-12   2928550.93                    1484
108     2024-01   2677498.55                    1340
109     2024-02   3542322.55                    1718
110     2024-03   1692854.89                     877
111     2024-04    483851.39                     246

[112 rows x 3 columns]

Date formatting - EXTRACT

In [17]:
%%sql

SELECT
  orderdate,
  EXTRACT(YEAR FROM orderdate) AS extract_year,
  EXTRACT(MONTH FROM orderdate) AS extract_month,
  EXTRACT(DAY FROM orderdate) AS extract_day
FROM
  sales
ORDER BY RANDOM()
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate extract_year extract_month extract_day
0  2019-07-11         2019             7          11
1  2018-03-06         2018             3           6
2  2021-09-10         2021             9          10
3  2023-08-09         2023             8           9
4  2023-02-18         2023             2          18
5  2020-01-15         2020             1          15
6  2021-10-06         2021            10           6
7  2023-12-21         2023            12          21
8  2023-07-01         2023             7           1
9  2023-08-25         2023             8          25

Analyze net revenue per order month

In [18]:
%%sql

SELECT
  EXTRACT(YEAR FROM orderdate) AS order_year,
  EXTRACT(MONTH FROM orderdate) AS order_month,
  SUM(quantity * netprice * exchangerate) AS net_revenue
FROM
  sales
GROUP BY
  order_year,
  order_month
ORDER BY
  order_year,
  order_month

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

112 rows affected.

    order_year order_month  net_revenue
0         2015           1    384092.66
1         2015           2    706374.12
2         2015           3    332961.59
3         2015           4    160767.00
4         2015           5    548632.63
..         ...         ...          ...
107       2023          12   2928550.93
108       2024           1   2677498.55
109       2024           2   3542322.55
110       2024           3   1692854.89
111       2024           4    483851.39

[112 rows x 3 columns]

Order dates within the last 5 years using EXTRACT

In [19]:
%%sql

SELECT
  s.orderdate,
  p.categoryname,
  SUM(quantity * netprice * exchangerate) AS net_revenue
FROM
  sales AS s
LEFT JOIN product AS p ON s.productkey = p.productkey
WHERE EXTRACT(YEAR FROM orderdate) >= EXTRACT(YEAR FROM CURRENT_DATE) -5 --last 5 years
GROUP BY
  s.orderdate,
  p.categoryname
ORDER BY
  s.orderdate,
  p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

11171 rows affected.

        orderdate                   categoryname  net_revenue
0      2020-01-01                          Audio      5490.14
1      2020-01-01        Cameras and camcorders      18880.06
2      2020-01-01                    Cell phones     22593.00
3      2020-01-01                      Computers     78554.54
4      2020-01-01                 Games and Toys      1476.43
...           ...                            ...          ...
11166  2024-04-20                      Computers     58353.68
11167  2024-04-20                 Games and Toys      1744.30
11168  2024-04-20                Home Appliances      1562.04
11169  2024-04-20  Music, Movies and Audio Books      4949.43
11170  2024-04-20                   TV and Video      9841.91

[11171 rows x 3 columns]

Order dates within the last 5 years using CURRENT_DATE to be more precise

In [20]:
%%sql

SELECT
  s.orderdate,
  p.categoryname,
  SUM(quantity * netprice * exchangerate) AS net_revenue
FROM
  sales AS s
LEFT JOIN product AS p ON s.productkey = p.productkey
WHERE orderdate >= CURRENT_DATE - INTERVAL '5 years' --last 5 years to this date
GROUP BY
  s.orderdate,
  p.categoryname
ORDER BY
  s.orderdate,
  p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

9731 rows affected.

       orderdate                   categoryname  net_revenue
0     2020-08-07        Cameras and camcorders        562.72
1     2020-08-07                    Cell phones      6370.84
2     2020-08-07                      Computers      9836.04
3     2020-08-07                 Games and Toys        63.12
4     2020-08-07  Music, Movies and Audio Books       777.36
...          ...                            ...          ...
9726  2024-04-20                      Computers     58353.68
9727  2024-04-20                 Games and Toys      1744.30
9728  2024-04-20                Home Appliances      1562.04
9729  2024-04-20  Music, Movies and Audio Books      4949.43
9730  2024-04-20                   TV and Video      9841.91

[9731 rows x 3 columns]

Average processing time by year

In [21]:
%%sql

SELECT
  CAST(DATE_PART('year', orderdate) AS INTEGER) AS order_year,
  ROUND(AVG(EXTRACT(DAYS FROM AGE(deliverydate, orderdate))), 2) AS avg_processing_time,
  CAST(ROUND(SUM(quantity * netprice * exchangerate)) AS INTEGER) AS net_revenue
FROM
  sales
WHERE orderdate >= CURRENT_DATE - INTERVAL '5 years'
GROUP BY
  order_year
ORDER BY
  order_year

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

5 rows affected.

   order_year avg_processing_time  net_revenue
0        2020                1.01      2012419
1        2021                1.36     21357977
2        2022                1.62     44864557
3        2023                1.75     33108566
4        2024                1.67      8396527

Window functions - average revenue of customers

In [22]:
%%sql

SELECT
  customerkey,
  orderkey,
  linenumber,
  (quantity * netprice * exchangerate) AS NET_revenue,
  AVG(quantity * netprice * exchangerate) OVER() AS avg_net_revenue_all_orders,
  AVG(quantity * netprice * exchangerate) OVER(PARTITION BY customerkey) AS avg_net_revenue_customer
FROM
  sales
ORDER BY customerkey
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,customerkey,orderkey,linenumber,net_revenue,avg_net_revenue_all_orders,avg_net_revenue_customer
0,15,2259001,0,2217.41,1032.69,2217.41
1,180,1305016,0,525.31,1032.69,836.74
2,180,3162018,0,71.36,1032.69,836.74
3,180,3162018,1,1913.55,1032.69,836.74
4,185,1613010,0,1395.52,1032.69,1395.52
5,243,505008,0,287.67,1032.69,287.67
6,387,1451007,3,45.62,1032.69,517.32
7,387,1451007,2,97.05,1032.69,517.32
8,387,1451007,0,1608.10,1032.69,517.32
9,387,1451007,1,619.77,1032.69,517.32

Window functions - percent daily revenue based on order line item

In [23]:
%%sql

SELECT
  orderdate,
  orderkey * 10 + linenumber AS order_linenumber,
  (quantity * netprice * exchangerate) AS NET_revenue,
  SUM(quantity * netprice * exchangerate) OVER(PARTITION BY orderdate) AS daily_net_revenue,
  (quantity * netprice * exchangerate) * 100 / SUM(quantity * netprice * exchangerate) OVER(PARTITION BY orderdate) AS percent_daily_revenue
FROM
  sales
ORDER BY
  orderdate,
  percent_daily_revenue DESC

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

199873 rows affected.

,orderdate,order_linenumber,net_revenue,daily_net_revenue,percent_daily_revenue
0,2015-01-01,10043,2395.10,11640.80,20.58
1,2015-01-01,10061,1552.32,11640.80,13.34
2,2015-01-01,10022,1302.91,11640.80,11.19
3,2015-01-01,10020,1146.75,11640.80,9.85
4,2015-01-01,10050,975.16,11640.80,8.38
...,...,...,...,...,...
199868,2024-04-20,33980141,12.00,96879.43,0.01
199869,2024-04-20,33980074,9.29,96879.43,0.01
199870,2024-04-20,33980080,8.35,96879.43,0.01
199871,2024-04-20,33980142,8.34,96879.43,0.01
199872,2024-04-20,33980310,6.89,96879.43,0.01

Cleaner version of same code using CTE

In [24]:
%%sql

SELECT *,
  100 * net_revenue / daily_net_revenue AS percent_daily_revenue
FROM(
  SELECT
    orderdate,
    orderkey * 10 + linenumber AS order_linenumber,
    (quantity * netprice * exchangerate) AS NET_revenue,
    SUM(quantity * netprice * exchangerate) OVER(PARTITION BY orderdate) AS daily_net_revenue
  FROM
    sales
) AS revenue_by_day

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

199873 rows affected.

,orderdate,order_linenumber,net_revenue,daily_net_revenue,percent_daily_revenue
0,2015-01-01,10000,63.49,11640.80,0.55
1,2015-01-01,10001,423.28,11640.80,3.64
2,2015-01-01,10010,108.75,11640.80,0.93
3,2015-01-01,10020,1146.75,11640.80,9.85
4,2015-01-01,10021,950.25,11640.80,8.16
...,...,...,...,...,...
199868,2024-04-20,33980341,914.61,96879.43,0.94
199869,2024-04-20,33980342,150.18,96879.43,0.16
199870,2024-04-20,33980350,147.78,96879.43,0.15
199871,2024-04-20,33980351,2019.62,96879.43,2.08
199872,2024-04-20,33980352,56.83,96879.43,0.06

Window functions - customer cohort year based on first order date

In [25]:
%%sql

WITH yearly_cohort AS (
  SELECT
    DISTINCT customerkey,
    EXTRACT(YEAR FROM MIN(orderdate) OVER(PARTITION BY customerkey)) AS cohort_year
  FROM
    sales
)
SELECT
  y.cohort_year,
  EXTRACT(YEAR FROM s.orderdate) AS purchase_year,
  SUM(s.exchangerate * s.netprice * s.quantity) AS net_revenue
FROM
  sales AS s
LEFT JOIN yearly_cohort AS y ON s.customerkey = y.customerkey
GROUP BY
  y.cohort_year,
  purchase_year

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

55 rows affected.

   cohort_year purchase_year  net_revenue
0         2019          2022   4848980.74
1         2020          2020   7265759.44
2         2018          2022   4534295.81
3         2017          2018   1407065.13
4         2016          2022   2164681.10
5         2021          2021  12635597.87
6         2018          2024    936833.89
7         2018          2023   3271753.92
8         2023          2023  14345184.96
9         2020          2024    312983.02
10        2016          2018   1074607.29
11        2016          2024    364066.76
12        2017          2020    625928.03
13        2019          2020   1295044.99
14        2021          2023   2242369.63
15        2018          2020   1171126.65
16        2022          2022  24412138.13
17        2016          2016   9990990.20
18        2017          2021   1329858.72
19        2021          2022   3014082.50
20        2019          2024    751725.53
21        2016          2021    964417.85
22        2020          2023   1435051.04
23        2021          2024    495686.18
24        2015          2018   1069850.87
25        2015          2020    386489.60
26        2018          2019   3229188.22
27        2015          2022   1569787.72
28        2015          2021    872845.99
29        2016          2019   1565400.72
30        2016          2020    474087.09
31        2017          2024    464802.56
32        2019          2021   2337594.77
33        2022          2023   4237220.04
34        2018          2021   2201262.39
35        2018          2018  21115924.55
36        2017          2019   1764716.90
37        2024          2024   2856649.33
38        2020          2022   1891708.40
39        2019          2019  24022798.65
40        2020          2021   1016399.07
41        2015          2015   7370979.48
42        2017          2023   1714010.18
43        2015          2017    479841.31
44        2019          2023   3440099.20
45        2017          2022   2428882.80
46        2022          2024   1223450.12
47        2016          2023   1265242.63
48        2015          2016    392623.48
49        2015          2024    356186.62
50        2023          2024    634143.37
51        2016          2017    497028.11
52        2015          2019   1235991.48
53        2017          2017  12244469.63
54        2015          2023   1157633.91

Window functions - unique customers per year by cohort

In [26]:
%%sql

WITH yearly_cohort AS (
SELECT DISTINCT
  customerkey,
  EXTRACT(YEAR FROM MIN(orderdate) OVER (PARTITION BY customerkey)) AS cohort_year,
  EXTRACT(YEAR FROM orderdate) AS purchase_year
FROM
  sales
)
SELECT DISTINCT
  cohort_year,
  purchase_year,
  COUNT(customerkey) OVER (PARTITION BY purchase_year, cohort_year) AS num_customers
FROM
  yearly_cohort
ORDER BY
  cohort_year,
  purchase_year

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

55 rows affected.

   cohort_year purchase_year  num_customers
0         2015          2015           2825
1         2015          2016            126
2         2015          2017            149
3         2015          2018            348
4         2015          2019            388
5         2015          2020            171
6         2015          2021            295
7         2015          2022            600
8         2015          2023            499
9         2015          2024            146
10        2016          2016           3397
11        2016          2017            174
12        2016          2018            374
13        2016          2019            457
14        2016          2020            205
15        2016          2021            336
16        2016          2022            746
17        2016          2023            573
18        2016          2024            183
19        2017          2017           4068
20        2017          2018            473
21        2017          2019            570
22        2017          2020            251
23        2017          2021            450
24        2017          2022            943
25        2017          2023            738
26        2017          2024            246
27        2018          2018           7446
28        2018          2019           1081
29        2018          2020            475
30        2018          2021            779
31        2018          2022           1644
32        2018          2023           1407
33        2018          2024            426
34        2019          2019           7755
35        2019          2020            523
36        2019          2021            873
37        2019          2022           1700
38        2019          2023           1439
39        2019          2024            370
40        2020          2020           3031
41        2020          2021            358
42        2020          2022            694
43        2020          2023            547
44        2020          2024            163
45        2021          2021           4663
46        2021          2022           1051
47        2021          2023            889
48        2021          2024            268
49        2022          2022           9010
50        2022          2023           1764
51        2022          2024            561
52        2023          2023           5890
53        2023          2024            332
54        2024          2024           1402

Window functions - using CTE when using a GROUP BY statement

In [27]:
%%sql

WITH customer_orders AS (
  SELECT
    customerkey,
    (quantity * exchangerate * netprice) AS order_value,
    COUNT(*) OVER(PARTITION BY customerkey) AS total_orders
  FROM
    sales
)
SELECT
  customerkey,
  total_orders,
  AVG(order_value) AS net_revenue
FROM
  customer_orders
GROUP BY
  customerkey,
  total_orders

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

49487 rows affected.

       customerkey  total_orders  net_revenue
0           149320             1        10.78
1           683627             1        56.66
2           438934            13       755.21
3           130312             3      1764.13
4           539962            15      2027.43
...            ...           ...          ...
49482      1001300             1       165.68
49483       966908             1      3874.71
49484      1018783             1       198.54
49485      1905553             7      1224.54
49486      1983421             6       654.09

[49487 rows x 3 columns]

Window functions - cohort analysis with average customer liftetime value (LTV)

In [28]:
%%sql

WITH yearly_cohort AS(
  SELECT
    customerkey,
    EXTRACT(YEAR FROM MIN(orderdate)) AS cohort_year,
    SUM(quantity * exchangerate * netprice) AS customer_ltv
  FROM
    sales
  GROUP BY
    customerkey
)
SELECT
  *,
  AVG(customer_ltv) OVER (PARTITION BY cohort_year) AS avg_cohort_ltv
FROM
  yearly_cohort
ORDER BY
  cohort_year,
  customerkey

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

49487 rows affected.

       customerkey cohort_year  customer_ltv  avg_cohort_ltv
0             4376        2015        182.00         5271.59
1             4403        2015       9530.35         5271.59
2             4925        2015       6078.08         5271.59
3             5729        2015        192.16         5271.59
4             6048        2015       1903.89         5271.59
...            ...         ...           ...             ...
49482      2093965        2024        475.22         2037.55
49483      2095129        2024        156.00         2037.55
49484      2095691        2024        326.00         2037.55
49485      2096470        2024        535.78         2037.55
49486      2097541        2024       1143.15         2037.55

[49487 rows x 4 columns]

Window functions - using WHERE to filter before invoking window function

In [29]:
%%sql

SELECT
  customerkey,
  EXTRACT(YEAR FROM MIN(orderdate) OVER (PARTITION BY customerkey)) AS cohort_year
FROM
  sales
WHERE orderdate >= '2020-01-01'

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

124451 rows affected.

        customerkey cohort_year
0                15        2021
1               180        2023
2               180        2023
3               387        2021
4               387        2021
...             ...         ...
124446      2099697        2022
124447      2099697        2022
124448      2099743        2022
124449      2099743        2022
124450      2099743        2022

[124451 rows x 2 columns]

Window functions - using WHERE to filter after invoking window function using CTE or subquery

In [30]:
%%sql

WITH cohort AS(
SELECT
  customerkey,
  EXTRACT(YEAR FROM MIN(orderdate) OVER (PARTITION BY customerkey)) AS cohort_year
FROM
  sales
)
SELECT *
FROM cohort
WHERE cohort_year >= '2020'

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

81370 rows affected.

       customerkey cohort_year
0               15        2021
1              406        2021
2              406        2021
3              545        2023
4              545        2023
...            ...         ...
81365      2099697        2022
81366      2099697        2022
81367      2099743        2022
81368      2099743        2022
81369      2099743        2022

[81370 rows x 2 columns]

Window functions - ORDER BY, running order count, & running average revenue

In [31]:
%%sql

SELECT
   customerkey,
   orderdate,
   (quantity * exchangerate * netprice) AS net_revenue,
   COUNT(*) OVER (
    PARTITION BY customerkey
    ORDER BY orderdate
   ) AS running_order_count,
   AVG(quantity * exchangerate * netprice) OVER (
    PARTITION BY customerkey
    ORDER BY orderdate
   ) AS running_avg_revenue
FROM
  sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

199873 rows affected.

,customerkey,orderdate,net_revenue,running_order_count,running_avg_revenue
0,15,2021-03-08,2217.41,1,2217.41
1,180,2018-07-28,525.31,1,525.31
2,180,2023-08-28,71.36,3,836.74
3,180,2023-08-28,1913.55,3,836.74
4,185,2019-06-01,1395.52,1,1395.52
...,...,...,...,...,...
199868,2099711,2016-08-13,2067.75,1,2067.75
199869,2099711,2017-08-14,3940.92,2,3004.34
199870,2099743,2022-03-17,375.57,2,234.81
199871,2099743,2022-03-17,94.05,2,234.81
199872,2099743,2023-02-11,598.46,3,356.03

Window functions - assigning row numbers

In [44]:
%%sql

SELECT
   ROW_NUMBER() OVER (
    PARTITION BY
      orderdate
    ORDER BY
      orderdate,
      orderkey,
      linenumber
   ) AS row_number,
   *
FROM
  sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

199873 rows affected.

,row_number,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64
1,2,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64
2,3,1001,0,2015-01-01,2015-01-01,1772036,430,1730,2,54.38,54.38,25.00,USD,1.00
3,4,1002,0,2015-01-01,2015-01-01,1518349,660,955,4,315.04,286.69,144.88,USD,1.00
4,5,1002,1,2015-01-01,2015-01-01,1518349,660,62,7,135.75,135.75,62.43,USD,1.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199868,93,3398034,1,2024-04-20,2024-04-21,664396,999999,1651,7,159.99,139.19,73.57,EUR,0.94
199869,94,3398034,2,2024-04-20,2024-04-21,664396,999999,1646,1,159.99,159.99,73.57,EUR,0.94
199870,95,3398035,0,2024-04-20,2024-04-22,267690,999999,1575,2,60.99,53.67,28.05,CAD,1.38
199871,96,3398035,1,2024-04-20,2024-04-22,267690,999999,415,5,326.00,293.40,166.20,CAD,1.38
199872,97,3398035,2,2024-04-20,2024-04-22,267690,999999,1693,6,6.88,6.88,3.16,CAD,1.38

Window functions - ranking customer order quantity

In [50]:
%%sql

SELECT
  customerkey,
  COUNT(*) AS total_orders,
  ROW_NUMBER() OVER(
    ORDER BY COUNT(*) DESC
  ) AS total_orders_row_num,
  RANK() OVER(
    ORDER BY COUNT(*) DESC
  ) AS total_orders_rank,
  DENSE_RANK() OVER(
    ORDER BY COUNT(*) DESC
  ) AS total_orders_dense_rank
FROM
  sales
GROUP BY customerkey
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,customerkey,total_orders,total_orders_row_num,total_orders_rank,total_orders_dense_rank
0,1834524,31,1,1,1
1,1375597,30,2,2,2
2,249557,27,3,3,3
3,459519,26,4,4,4
4,1495941,26,5,4,4
5,1801215,26,6,4,4
6,1219056,25,7,7,5
7,759419,24,8,8,6
8,1427444,24,9,8,6
9,1876222,24,10,8,6

Window functions - first value, last value, nth value, lead, lag examples

In [61]:
%%sql

WITH monthly_revenue AS(
  SELECT
    TO_CHAR(orderdate, 'YYYY-MM') AS month,
    SUM(quantity * netprice * exchangerate) AS net_revenue
  FROM
    sales
  WHERE EXTRACT(YEAR FROM orderdate) = 2023
  GROUP BY month
  ORDER BY month
)
SELECT
  *,
  FIRST_VALUE(net_revenue) OVER(ORDER BY month) AS first_month_revenue,
  LAST_VALUE(net_revenue) OVER(ORDER BY month ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS last_month_revenue,
  NTH_VALUE(net_revenue, 3) OVER(ORDER BY month) AS third_month_revenue,
  LAG(net_revenue) OVER(ORDER BY month) AS previous_month_revenue,
  LEAD(net_revenue) OVER(ORDER BY month) AS next_month_revenue
FROM monthly_revenue

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

,month,net_revenue,first_month_revenue,last_month_revenue,third_month_revenue,previous_month_revenue,next_month_revenue
0,2023-01,3664431.34,3664431.34,2928550.93,NaN,NaN,4465204.57
1,2023-02,4465204.57,3664431.34,2928550.93,NaN,3664431.34,2244316.52
2,2023-03,2244316.52,3664431.34,2928550.93,2244316.52,4465204.57,1162796.16
3,2023-04,1162796.16,3664431.34,2928550.93,2244316.52,2244316.52,2943005.99
4,2023-05,2943005.99,3664431.34,2928550.93,2244316.52,1162796.16,2864500.03
5,2023-06,2864500.03,3664431.34,2928550.93,2244316.52,2943005.99,2337639.34
6,2023-07,2337639.34,3664431.34,2928550.93,2244316.52,2864500.03,2623919.79
7,2023-08,2623919.79,3664431.34,2928550.93,2244316.52,2337639.34,2622774.85
8,2023-09,2622774.85,3664431.34,2928550.93,2244316.52,2623919.79,2551322.61
9,2023-10,2551322.61,3664431.34,2928550.93,2244316.52,2622774.85,2700103.38
10,2023-11,2700103.38,3664431.34,2928550.93,2244316.52,2551322.61,2928550.93
11,2023-12,2928550.93,3664431.34,2928550.93,2244316.52,2700103.38,NaN

Window functions - month over month revenue growth

In [66]:
%%sql

WITH monthly_revenue AS(
  SELECT
    TO_CHAR(orderdate, 'YYYY-MM') AS month,
    SUM(quantity * netprice * exchangerate) AS net_revenue
  FROM
    sales
  WHERE EXTRACT(YEAR FROM orderdate) = 2023
  GROUP BY month
  ORDER BY month
)
SELECT
  *,
  LAG(net_revenue) OVER(ORDER BY month) AS previous_month_revenue,
  100 * (net_revenue - LAG(net_revenue) OVER(ORDER BY month)) / LAG(net_revenue) OVER(ORDER BY month) AS percent_monthly_revenue_growth
FROM monthly_revenue

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

,month,net_revenue,previous_month_revenue,percent_monthly_revenue_growth
0,2023-01,3664431.34,NaN,NaN
1,2023-02,4465204.57,3664431.34,21.85
2,2023-03,2244316.52,4465204.57,-49.74
3,2023-04,1162796.16,2244316.52,-48.19
4,2023-05,2943005.99,1162796.16,153.10
5,2023-06,2864500.03,2943005.99,-2.67
6,2023-07,2337639.34,2864500.03,-18.39
7,2023-08,2623919.79,2337639.34,12.25
8,2023-09,2622774.85,2623919.79,-0.04
9,2023-10,2551322.61,2622774.85,-2.72
10,2023-11,2700103.38,2551322.61,5.83
11,2023-12,2928550.93,2700103.38,8.46

Window functions - monthly revenue drops

In [72]:
%%sql

WITH yearly_cohort AS (
  SELECT
    customerkey,
    EXTRACT(YEAR FROM MIN(orderdate)) AS cohort_year,
    SUM(quantity * exchangerate * netprice) AS customer_ltv
  FROM
    sales
  GROUP BY
    customerkey
), cohort_summary AS (
    SELECT
      cohort_year,
      customerkey,
      customer_ltv,
      AVG(customer_ltv) OVER (PARTITION BY cohort_year) AS avg_cohort_ltv
    FROM
      yearly_cohort
    ORDER BY
      cohort_year,
      customerkey
), cohort_final AS (
SELECT DISTINCT
  cohort_year,
  avg_cohort_ltv
FROM cohort_summary
ORDER BY
  cohort_year
)
SELECT
  *,
  LAG(avg_cohort_ltv) OVER(ORDER BY cohort_year) AS previous_cohort_ltv,
  100 * (avg_cohort_ltv - LAG(avg_cohort_ltv) OVER(ORDER BY cohort_year)) / LAG(avg_cohort_ltv) OVER(ORDER BY cohort_year) AS percent_ltv_change
FROM cohort_final

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

  cohort_year  avg_cohort_ltv  previous_cohort_ltv  percent_ltv_change
0        2015         5271.59                  NaN                 NaN
1        2016         5404.92              5271.59                2.53
2        2017         5403.08              5404.92               -0.03
3        2018         4896.64              5403.08               -9.37
4        2019         4731.95              4896.64               -3.36
5        2020         3933.32              4731.95              -16.88
6        2021         3943.33              3933.32                0.25
7        2022         3315.52              3943.33              -15.92
8        2023         2543.18              3315.52              -23.29
9        2024         2037.55              2543.18              -19.88

Window functions - frame clauses, 2023 monthly net revenue

In [73]:
%%sql

SELECT
  TO_CHAR(orderdate, 'YYYY-MM') AS month,
  SUM(quantity * netprice * exchangerate) AS net_revenue
FROM
  sales
WHERE EXTRACT(YEAR FROM orderdate) = 2023
GROUP BY month
ORDER BY month

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

      month  net_revenue
0   2023-01   3664431.34
1   2023-02   4465204.57
2   2023-03   2244316.52
3   2023-04   1162796.16
4   2023-05   2943005.99
5   2023-06   2864500.03
6   2023-07   2337639.34
7   2023-08   2623919.79
8   2023-09   2622774.85
9   2023-10   2551322.61
10  2023-11   2700103.38
11  2023-12   2928550.93