<a href="https://colab.research.google.com/github/ljtallon/SQL_Projects/blob/main/Resources/Blank_SQL_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [3]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

Connecting and switching to connection 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [4]:
%%sql

SELECT *
FROM sales
LIMIT 10;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64
1,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64
2,1001,0,2015-01-01,2015-01-01,1772036,430,1730,2,54.38,54.38,25.00,USD,1.00
3,1002,0,2015-01-01,2015-01-01,1518349,660,955,4,315.04,286.69,144.88,USD,1.00
4,1002,1,2015-01-01,2015-01-01,1518349,660,62,7,135.75,135.75,62.43,USD,1.00
5,1002,2,2015-01-01,2015-01-01,1518349,660,1050,3,499.20,434.30,229.57,USD,1.00
6,1002,3,2015-01-01,2015-01-01,1518349,660,1608,1,65.99,58.73,33.65,USD,1.00
7,1003,0,2015-01-01,2015-01-01,1317097,510,85,3,74.99,74.99,34.48,USD,1.00
8,1004,0,2015-01-01,2015-01-01,254117,80,128,2,114.72,113.57,58.49,CAD,1.16
9,1004,1,2015-01-01,2015-01-01,254117,80,2079,1,499.45,499.45,165.48,CAD,1.16

In [8]:
%%sql

SELECT *
FROM information_schema.columns
WHERE table_name = 'customer'

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

24 rows affected.

,table_catalog,table_schema,table_name,column_name,ordinal_position,column_default,is_nullable,data_type,character_maximum_length,character_octet_length,...,is_identity,identity_generation,identity_start,identity_increment,identity_maximum,identity_minimum,identity_cycle,is_generated,generation_expression,is_updatable
0,contoso_100k,public,customer,customerkey,1,None,NO,integer,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
1,contoso_100k,public,customer,geoareakey,2,None,YES,integer,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
2,contoso_100k,public,customer,startdt,3,None,YES,date,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
3,contoso_100k,public,customer,enddt,4,None,YES,date,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
4,contoso_100k,public,customer,birthday,18,None,YES,date,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
5,contoso_100k,public,customer,age,19,None,YES,integer,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
6,contoso_100k,public,customer,latitude,23,None,YES,double precision,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
7,contoso_100k,public,customer,longitude,24,None,YES,double precision,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
8,contoso_100k,public,customer,middleinitial,9,None,YES,character varying,5.00,20.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
9,contoso_100k,public,customer,surname,10,None,YES,character varying,50.00,200.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
10,contoso_100k,public,customer,streetaddress,11,None,YES,character varying,100.00,400.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
11,contoso_100k,public,customer,city,12,None,YES,character varying,50.00,200.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
12,contoso_100k,public,customer,state,13,None,YES,character varying,50.00,200.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
13,contoso_100k,public,customer,statefull,14,None,YES,character varying,100.00,400.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
14,contoso_100k,public,customer,zipcode,15,None,YES,character varying,20.00,80.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
15,contoso_100k,public,customer,country,16,None,YES,character varying,50.00,200.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
16,contoso_100k,public,customer,countryfull,17,None,YES,character varying,100.00,400.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
17,contoso_100k,public,customer,company,21,None,YES,character varying,100.00,400.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
18,contoso_100k,public,customer,vehicle,22,None,YES,character varying,100.00,400.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
19,contoso_100k,public,customer,occupation,20,None,YES,character varying,100.00,400.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
20,contoso_100k,public,customer,continent,5,None,YES,character varying,50.00,200.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
21,contoso_100k,public,customer,gender,6,None,YES,character varying,10.00,40.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
22,contoso_100k,public,customer,title,7,None,YES,character varying,20.00,80.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
23,contoso_100k,public,customer,givenname,8,None,YES,character varying,50.00,200.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES

In [14]:
%%sql

SELECT orderdate,
  quantity * netprice * exchangerate AS net_revenue
FROM sales
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate  net_revenue
0  2015-01-01        63.49
1  2015-01-01       423.28
2  2015-01-01       108.75
3  2015-01-01      1146.75
4  2015-01-01       950.25
5  2015-01-01      1302.91
6  2015-01-01        58.73
7  2015-01-01       224.98
8  2015-01-01       263.11
9  2015-01-01       578.52

Recent sales >= 2020

In [18]:
%%sql

SELECT orderdate,
  quantity * netprice * exchangerate AS net_revenue
FROM sales
WHERE orderdate::DATE >= '2020-01-01'
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate  net_revenue
0  2020-01-01        99.47
1  2020-01-01       139.97
2  2020-01-01       669.39
3  2020-01-01      4090.60
4  2020-01-01       237.15
5  2020-01-01      1507.16
6  2020-01-01       189.35
7  2020-01-01       539.90
8  2020-01-01      5590.00
9  2020-01-01      3580.00

Add customer info

In [25]:
%%sql

SELECT
  s.orderdate,
  s.quantity * s.netprice * s.exchangerate AS net_revenue,
  c.givenname,
  c.surname,
  c.countryfull,
  c.continent,
  p.productkey,
  p.productname,
  p.categoryname,
  p.subcategoryname
FROM
  sales AS s
LEFT JOIN customer AS c ON s.customerkey = c.customerkey
LEFT JOIN product AS p ON s.productkey = p.productkey
WHERE
  orderdate::DATE >= '2020-01-01'
LIMIT
  10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,orderdate,net_revenue,givenname,surname,countryfull,continent,productkey,productname,categoryname,subcategoryname
0,2020-01-01,99.47,Heike,Burger,Germany,Europe,1810,MGS Bicycle Card Games2009 E166,Games and Toys,Download Games
1,2020-01-01,139.97,Heike,Burger,Germany,Europe,1809,MGS Bicycle Board Games2009 E165,Games and Toys,Download Games
2,2020-01-01,669.39,Heike,Burger,Germany,Europe,698,Proseware Wireless Photo All-in-One Printer M3...,Computers,"Printers, Scanners & Fax"
3,2020-01-01,4090.60,Heike,Burger,Germany,Europe,364,Adventure Works Laptop12 M1200 Black,Computers,Laptops
4,2020-01-01,237.15,Michelle,Seeber,Canada,North America,1288,Contoso Genuine Leather Grip Belt E322 Silver,Cameras and camcorders,Cameras & Camcorders Accessories
5,2020-01-01,1507.16,Jason,Smith,United States,North America,2061,Contoso Microwave 1.5CuFt X0110 Silver,Home Appliances,Microwaves
6,2020-01-01,189.35,Jason,Smith,United States,North America,1717,MGS Flight Simulator X M250,Games and Toys,Download Games
7,2020-01-01,539.90,Jason,Smith,United States,North America,435,Adventure Works Desktop PC1.60 ED160 White,Computers,Desktops
8,2020-01-01,5590.00,James,Frye,United States,North America,451,WWI Desktop PC2.30 M2300 Silver,Computers,Desktops
9,2020-01-01,3580.00,Johnny,Couch,United States,North America,535,WWI LCD19W M100 White,Computers,Monitors

High vs low ($1,000)

In [28]:
%%sql

SELECT
  s.orderdate,
  s.quantity * s.netprice * s.exchangerate AS net_revenue,
  c.givenname,
  c.surname,
  c.countryfull,
  c.continent,
  p.productkey,
  p.productname,
  p.categoryname,
  p.subcategoryname,
  CASE WHEN s.quantity * s.netprice * s.exchangerate > 1000 THEN 'HIGH' ELSE 'LOW' END AS high_low
FROM
  sales AS s
LEFT JOIN customer AS c ON s.customerkey = c.customerkey
LEFT JOIN product AS p ON s.productkey = p.productkey
WHERE
  orderdate::DATE >= '2020-01-01'

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

124451 rows affected.

,orderdate,net_revenue,givenname,surname,countryfull,continent,productkey,productname,categoryname,subcategoryname,high_low
0,2020-01-01,3075.80,David,Stone,United States,North America,1051,"A. Datum SLR Camera 35"" M358 Silver",Cameras and camcorders,Digital SLR Cameras,HIGH
1,2020-01-01,444.34,David,Stone,United States,North America,1709,MGS Gears of War M170,Games and Toys,Download Games,LOW
2,2020-01-01,1187.73,David,Stone,United States,North America,457,WWI Desktop PC1.60 E1600 White,Computers,Desktops,HIGH
3,2020-01-01,36.78,David,Stone,United States,North America,1385,Contoso Multi-line phones M30 Grey,Cell phones,Home & Office Phones,LOW
4,2020-01-01,4.45,David,Stone,United States,North America,1665,MGS Hand Games for 12-16 boys E600 Yellow,Games and Toys,Boxed Games,LOW
...,...,...,...,...,...,...,...,...,...,...,...
124446,2024-04-20,14.35,Guus,Doodeman,Netherlands,Europe,849,Contoso Ultraportable Neoprene Sleeve E30 Green,Computers,Computers Accessories,LOW
124447,2024-04-20,261.32,Guus,Doodeman,Netherlands,Europe,1651,Contoso DVD 9-Inch Player Portable M300 Silver,"Music, Movies and Audio Books",Movie DVD,LOW
124448,2024-04-20,147.78,Michael,Wilson,Canada,North America,1575,SV DVD Player M140 Gold,"Music, Movies and Audio Books",Movie DVD,LOW
124449,2024-04-20,2019.62,Michael,Wilson,Canada,North America,415,Proseware Laptop8.9 E089 White,Computers,Laptops,HIGH
124450,2024-04-20,56.83,Michael,Wilson,Canada,North America,1693,SV Hand Games men M30 Black,Games and Toys,Boxed Games,LOW