<a href="https://colab.research.google.com/github/ljtallon/SQL_Projects/blob/main/Resources/Blank_SQL_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [2]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [3]:
%%sql

SELECT *
FROM sales
LIMIT 10;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64
1,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64
2,1001,0,2015-01-01,2015-01-01,1772036,430,1730,2,54.38,54.38,25.00,USD,1.00
3,1002,0,2015-01-01,2015-01-01,1518349,660,955,4,315.04,286.69,144.88,USD,1.00
4,1002,1,2015-01-01,2015-01-01,1518349,660,62,7,135.75,135.75,62.43,USD,1.00
5,1002,2,2015-01-01,2015-01-01,1518349,660,1050,3,499.20,434.30,229.57,USD,1.00
6,1002,3,2015-01-01,2015-01-01,1518349,660,1608,1,65.99,58.73,33.65,USD,1.00
7,1003,0,2015-01-01,2015-01-01,1317097,510,85,3,74.99,74.99,34.48,USD,1.00
8,1004,0,2015-01-01,2015-01-01,254117,80,128,2,114.72,113.57,58.49,CAD,1.16
9,1004,1,2015-01-01,2015-01-01,254117,80,2079,1,499.45,499.45,165.48,CAD,1.16

In [4]:
%%sql

SELECT *
FROM information_schema.columns
WHERE table_name = 'customer'

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

24 rows affected.

,table_catalog,table_schema,table_name,column_name,ordinal_position,column_default,is_nullable,data_type,character_maximum_length,character_octet_length,...,is_identity,identity_generation,identity_start,identity_increment,identity_maximum,identity_minimum,identity_cycle,is_generated,generation_expression,is_updatable
0,contoso_100k,public,customer,customerkey,1,None,NO,integer,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
1,contoso_100k,public,customer,geoareakey,2,None,YES,integer,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
2,contoso_100k,public,customer,startdt,3,None,YES,date,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
3,contoso_100k,public,customer,enddt,4,None,YES,date,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
4,contoso_100k,public,customer,birthday,18,None,YES,date,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
5,contoso_100k,public,customer,age,19,None,YES,integer,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
6,contoso_100k,public,customer,latitude,23,None,YES,double precision,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
7,contoso_100k,public,customer,longitude,24,None,YES,double precision,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
8,contoso_100k,public,customer,middleinitial,9,None,YES,character varying,5.00,20.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
9,contoso_100k,public,customer,surname,10,None,YES,character varying,50.00,200.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
10,contoso_100k,public,customer,streetaddress,11,None,YES,character varying,100.00,400.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
11,contoso_100k,public,customer,city,12,None,YES,character varying,50.00,200.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
12,contoso_100k,public,customer,state,13,None,YES,character varying,50.00,200.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
13,contoso_100k,public,customer,statefull,14,None,YES,character varying,100.00,400.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
14,contoso_100k,public,customer,zipcode,15,None,YES,character varying,20.00,80.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
15,contoso_100k,public,customer,country,16,None,YES,character varying,50.00,200.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
16,contoso_100k,public,customer,countryfull,17,None,YES,character varying,100.00,400.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
17,contoso_100k,public,customer,company,21,None,YES,character varying,100.00,400.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
18,contoso_100k,public,customer,vehicle,22,None,YES,character varying,100.00,400.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
19,contoso_100k,public,customer,occupation,20,None,YES,character varying,100.00,400.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
20,contoso_100k,public,customer,continent,5,None,YES,character varying,50.00,200.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
21,contoso_100k,public,customer,gender,6,None,YES,character varying,10.00,40.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
22,contoso_100k,public,customer,title,7,None,YES,character varying,20.00,80.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
23,contoso_100k,public,customer,givenname,8,None,YES,character varying,50.00,200.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES

In [5]:
%%sql

SELECT orderdate,
  quantity * netprice * exchangerate AS net_revenue
FROM sales
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate  net_revenue
0  2015-01-01        63.49
1  2015-01-01       423.28
2  2015-01-01       108.75
3  2015-01-01      1146.75
4  2015-01-01       950.25
5  2015-01-01      1302.91
6  2015-01-01        58.73
7  2015-01-01       224.98
8  2015-01-01       263.11
9  2015-01-01       578.52

Recent sales >= 2020

In [6]:
%%sql

SELECT orderdate,
  quantity * netprice * exchangerate AS net_revenue
FROM sales
WHERE orderdate::DATE >= '2020-01-01'
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate  net_revenue
0  2020-01-01        99.47
1  2020-01-01       139.97
2  2020-01-01       669.39
3  2020-01-01      4090.60
4  2020-01-01       237.15
5  2020-01-01      1507.16
6  2020-01-01       189.35
7  2020-01-01       539.90
8  2020-01-01      5590.00
9  2020-01-01      3580.00

Add customer info

In [7]:
%%sql

SELECT
  s.orderdate,
  s.quantity * s.netprice * s.exchangerate AS net_revenue,
  c.givenname,
  c.surname,
  c.countryfull,
  c.continent,
  p.productkey,
  p.productname,
  p.categoryname,
  p.subcategoryname
FROM
  sales AS s
LEFT JOIN customer AS c ON s.customerkey = c.customerkey
LEFT JOIN product AS p ON s.productkey = p.productkey
WHERE
  orderdate::DATE >= '2020-01-01'
LIMIT
  10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,orderdate,net_revenue,givenname,surname,countryfull,continent,productkey,productname,categoryname,subcategoryname
0,2020-01-01,99.47,Heike,Burger,Germany,Europe,1810,MGS Bicycle Card Games2009 E166,Games and Toys,Download Games
1,2020-01-01,139.97,Heike,Burger,Germany,Europe,1809,MGS Bicycle Board Games2009 E165,Games and Toys,Download Games
2,2020-01-01,669.39,Heike,Burger,Germany,Europe,698,Proseware Wireless Photo All-in-One Printer M3...,Computers,"Printers, Scanners & Fax"
3,2020-01-01,4090.60,Heike,Burger,Germany,Europe,364,Adventure Works Laptop12 M1200 Black,Computers,Laptops
4,2020-01-01,237.15,Michelle,Seeber,Canada,North America,1288,Contoso Genuine Leather Grip Belt E322 Silver,Cameras and camcorders,Cameras & Camcorders Accessories
5,2020-01-01,1507.16,Jason,Smith,United States,North America,2061,Contoso Microwave 1.5CuFt X0110 Silver,Home Appliances,Microwaves
6,2020-01-01,189.35,Jason,Smith,United States,North America,1717,MGS Flight Simulator X M250,Games and Toys,Download Games
7,2020-01-01,539.90,Jason,Smith,United States,North America,435,Adventure Works Desktop PC1.60 ED160 White,Computers,Desktops
8,2020-01-01,5590.00,James,Frye,United States,North America,451,WWI Desktop PC2.30 M2300 Silver,Computers,Desktops
9,2020-01-01,3580.00,Johnny,Couch,United States,North America,535,WWI LCD19W M100 White,Computers,Monitors

High vs low ($1,000)

In [8]:
%%sql

SELECT
  s.orderdate,
  s.quantity * s.netprice * s.exchangerate AS net_revenue,
  c.givenname,
  c.surname,
  c.countryfull,
  c.continent,
  p.productkey,
  p.productname,
  p.categoryname,
  p.subcategoryname,
  CASE WHEN s.quantity * s.netprice * s.exchangerate > 1000 THEN 'HIGH' ELSE 'LOW' END AS high_low
FROM
  sales AS s
LEFT JOIN customer AS c ON s.customerkey = c.customerkey
LEFT JOIN product AS p ON s.productkey = p.productkey
WHERE
  orderdate::DATE >= '2020-01-01'

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

124451 rows affected.

,orderdate,net_revenue,givenname,surname,countryfull,continent,productkey,productname,categoryname,subcategoryname,high_low
0,2020-01-18,302.27,Jamie,Hoddle,Australia,Australia,107,WWI Stereo Bluetooth Headphones New Generation...,Audio,Bluetooth Headphones,LOW
1,2020-01-18,833.71,Jamie,Hoddle,Australia,Australia,392,WWI Laptop12 M0120 Black,Computers,Laptops,LOW
2,2020-01-18,1572.73,Jamie,Hoddle,Australia,Australia,1464,Contoso Touch Screen Phones 5-Wire/On-wall M50...,Cell phones,Touch Screen Phones,HIGH
3,2020-01-18,48.20,Jamie,Hoddle,Australia,Australia,2501,Contoso Phone Tough Skin Case E140 Pink,Cell phones,Cell phones Accessories,LOW
4,2020-01-20,656.69,Leon,Schweitzer,Germany,Europe,2512,Contoso Bluetooth Active Headphones L15 Black,Cell phones,Cell phones Accessories,LOW
...,...,...,...,...,...,...,...,...,...,...,...
124446,2023-09-20,269.00,Andrea,Jones,United States,North America,1503,The Phone Company Smart phones 8 GB of Memory ...,Cell phones,Smart phones & PDAs,LOW
124447,2023-09-20,274.60,Manuela,Abendroth,Germany,Europe,1239,"Fabrikam Social Videographer 2/3"" 17mm E100 Blue",Cameras and camcorders,Camcorders,LOW
124448,2023-09-20,2468.43,Hudson,Warner,Australia,Australia,440,WWI Desktop PC1.60 E1600 Silver,Computers,Desktops,HIGH
124449,2023-09-20,42.92,Hudson,Warner,Australia,Australia,1821,MGS Combat Flight Simulator 2009 E177,Games and Toys,Download Games,LOW
124450,2023-09-20,2380.50,Edward,Nowak,United States,North America,1442,The Phone Company Touch Screen Phone 1600 TFT-...,Cell phones,Touch Screen Phones,HIGH

Total number of customers per order date

In [14]:
%%sql

SELECT
  orderdate,
  COUNT(DISTINCT(customerkey)) AS total_customers
FROM
  sales
WHERE
  orderdate BETWEEN '2023-01-01' AND '2023-12-31'
GROUP BY
  orderdate
ORDER BY
  orderdate

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

364 rows affected.

      orderdate  total_customers
0    2023-01-01               12
1    2023-01-02               49
2    2023-01-03               64
3    2023-01-04               78
4    2023-01-05               87
..          ...              ...
359  2023-12-27               73
360  2023-12-28               75
361  2023-12-29               55
362  2023-12-30               91
363  2023-12-31                9

[364 rows x 2 columns]

Customers by region

In [21]:
%%sql

SELECT
  s.orderdate,
  COUNT(DISTINCT CASE WHEN c.continent = 'Europe' THEN s.customerkey END) AS eu_customers,
  COUNT(DISTINCT CASE WHEN c.continent = 'North America' THEN s.customerkey END) AS na_customers,
  COUNT(DISTINCT CASE WHEN c.continent = 'Australia' THEN s.customerkey END) AS au_customers
FROM
  sales AS s
LEFT JOIN customer AS c ON s.customerkey = c.customerkey
WHERE
  s.orderdate BETWEEN '2023-01-01' AND '2023-12-31'
GROUP BY
  s.orderdate
ORDER BY
  s.orderdate

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

364 rows affected.

      orderdate  eu_customers  na_customers  au_customers
0    2023-01-01             6             5             1
1    2023-01-02            15            31             3
2    2023-01-03            17            44             3
3    2023-01-04            28            46             4
4    2023-01-05            22            57             8
..          ...           ...           ...           ...
359  2023-12-27            26            41             6
360  2023-12-28            24            44             7
361  2023-12-29            19            32             4
362  2023-12-30            25            50            16
363  2023-12-31             1             8             0

[364 rows x 4 columns]

Daily customers by region

In [36]:
%%sql

SELECT
  p.categoryname,
  SUM(CASE WHEN s.orderdate BETWEEN '2022-01-01' AND '2022-12-31' THEN (s.quantity * s.netprice * s.exchangerate) ELSE 0 END) AS total_net_revenue_2022,
  SUM(CASE WHEN s.orderdate BETWEEN '2023-01-01' AND '2023-12-31' THEN (s.quantity * s.netprice * s.exchangerate) ELSE 0 END) AS total_net_revenue_2023
FROM
  sales AS s
LEFT JOIN product AS p ON s.productkey = p.productkey
GROUP BY
  p.categoryname
ORDER BY
  p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

,categoryname,total_net_revenue_2022,total_net_revenue_2023
0,Audio,766938.21,688690.18
1,Cameras and camcorders,2382532.56,1983546.29
2,Cell phones,8119665.07,6002147.63
3,Computers,17862213.49,11650867.21
4,Games and Toys,316127.30,270374.96
5,Home Appliances,6612446.68,5919992.87
6,"Music, Movies and Audio Books",2989297.28,2180768.13
7,TV and Video,5815336.61,4412178.23

Aggregate functions with net revenue

In [38]:
%%sql

SELECT
  p.categoryname,
  AVG(CASE WHEN s.orderdate BETWEEN '2022-01-01' AND '2022-12-31' THEN (s.quantity * s.netprice * s.exchangerate) ELSE 0 END) AS avg_net_revenue_2022,
  AVG(CASE WHEN s.orderdate BETWEEN '2023-01-01' AND '2023-12-31' THEN (s.quantity * s.netprice * s.exchangerate) ELSE 0 END) AS avg_net_revenue_2023,
  MIN(CASE WHEN s.orderdate BETWEEN '2022-01-01' AND '2022-12-31' THEN (s.quantity * s.netprice * s.exchangerate) ELSE 0 END) AS min_net_revenue_2022,
  MIN(CASE WHEN s.orderdate BETWEEN '2023-01-01' AND '2023-12-31' THEN (s.quantity * s.netprice * s.exchangerate) ELSE 0 END) AS min_net_revenue_2023,
  MAX(CASE WHEN s.orderdate BETWEEN '2022-01-01' AND '2022-12-31' THEN (s.quantity * s.netprice * s.exchangerate) ELSE 0 END) AS max_net_revenue_2022,
  MAX(CASE WHEN s.orderdate BETWEEN '2023-01-01' AND '2023-12-31' THEN (s.quantity * s.netprice * s.exchangerate) ELSE 0 END) AS max_net_revenue_2023
FROM
  sales AS s
LEFT JOIN product AS p ON s.productkey = p.productkey
GROUP BY
  p.categoryname
ORDER BY
  p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

,categoryname,avg_net_revenue_2022,avg_net_revenue_2023,min_net_revenue_2022,min_net_revenue_2023,max_net_revenue_2022,max_net_revenue_2023
0,Audio,50.18,45.06,0.00,0.00,3473.36,2730.87
1,Cameras and camcorders,176.85,147.23,0.00,0.00,15008.39,13572.00
2,Cell phones,194.66,143.89,0.00,0.00,7692.37,8912.22
3,Computers,384.13,250.55,0.00,0.00,38082.66,27611.60
4,Games and Toys,15.60,13.34,0.00,0.00,5202.01,3357.30
5,Home Appliances,390.05,349.20,0.00,0.00,31654.55,32915.59
6,"Music, Movies and Audio Books",93.37,68.11,0.00,0.00,5415.19,3804.91
7,TV and Video,425.35,322.72,0.00,0.00,30259.41,27503.12

Median sales by category in postgreSQL

In [46]:
%%sql

SELECT
  p.categoryname,
  PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (CASE WHEN s.orderdate BETWEEN '2022-01-01' AND '2022-12-31' THEN (s.quantity * s.netprice * s.exchangerate) END)) AS y2022_median_sales,
  PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (CASE WHEN s.orderdate BETWEEN '2023-01-01' AND '2023-12-31' THEN (s.quantity * s.netprice * s.exchangerate) END)) AS y2023_median_sales
FROM
  sales AS s
LEFT JOIN product AS p ON s.productkey = p.productkey
GROUP BY
  p.categoryname
ORDER BY
  p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                    categoryname  y2022_median_sales  y2023_median_sales
0                          Audio              257.21              266.59
1        Cameras and camcorders               651.46              672.60
2                    Cell phones              418.60              375.88
3                      Computers              809.70              657.18
4                 Games and Toys               33.78               32.62
5                Home Appliances              791.00              825.25
6  Music, Movies and Audio Books              186.58              159.63
7                   TV and Video              730.46              790.79